version: "3"
services:
  cloud-reve:
    image: jialezi/cloudreve
    container_name: cloud-reve
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 443:5212
    volumes:
      - ./cloudreve/config:/cloudreve/config
      - ./cloudreve/uploads:/cloudreve/uploads
      - ./cloudreve/avatar:/cloudreve/avatar
    privileged: true
